### ISSUE TITLE
脚本跑不起来，实在是搞不懂了

### ISSUE THREAD

**Issue by M8-AGS** [akaimoe/BilibiliTicketRushBuy#16]
PS E:\qp\BilibiliTicketRushBuy-main> python Main.py
Traceback (most recent call last):
  File "C:\Users\wing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.10.0-py3.10.egg\selenium\webdriver\common\driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "C:\Users\wing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.10.0-py3.10.egg\selenium\webdriver\common\selenium_manager.py", line 76, in driver_location
    args = [str(self.get_binary()), "--browser", browser, "--output", "json"]
  File "C:\Users\wing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.10.0-py3.10.egg\selenium\webdriver\common\selenium_manager.py", line 60, in get_binary
    raise WebDriverException(f"Unable to obtain working Selenium Manager binary; {path}")
selenium.common.exceptions.WebDriverException: Message: Unable to obtain working Selenium Manager binary; C:\Users\wing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.10.0-py3.10.egg\selenium\webdriver\common\windows\selenium-manager.exe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\qp\BilibiliTicketRushBuy-main\Main.py", line 9, in <module>
    WebDriver = webdriver.Chrome()
  File "C:\Users\wing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.10.0-py3.10.egg\selenium\webdriver\chrome\webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "C:\Users\wing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.10.0-py3.10.egg\selenium\webdriver\common\driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; Message: Unable to obtain working Selenium Manager binary; C:\Users\wing\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.10.0-py3.10.egg\selenium\webdriver\common\windows\selenium-manager.exe
; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

有没有佬能帮忙看看到底是什么问题？
PS：pip命令不知道为什么死活用不了，手动安装的selemium。

**Comment by akaimoe** [comment]
pip命令用不了具体是什么情况？如果是网络问题的话可以根据刚刚更新版本的README中的方法来下载相关包，如果是pip本身的问题建议看看是不是有诸如没有pip添加到环境变量里面类似的问题。

**Comment by M8-AGS** [comment]
> pip命令用不了具体是什么情况？如果是网络问题的话可以根据刚刚更新版本的README中的方法来下载相关包，如果是pip本身的问题建议看看是不是有诸如没有pip添加到环境变量里面类似的问题。

是pip本身的问题，PowerShell找不到pip命令，但是环境变量已经配置过了。直接到scripts目录下运行pip是可以运行的。依赖包安装完毕以后运行Python命令就弹出了上面的报错。

**Comment by akaimoe** [comment]
嘶~建议你重新安装一下python，安装的过程中有个“添加pip到path”的选项，把这个勾选了，pip会自动配置好。按道理说PowerShell是可以直接找到pip的，感觉还是你pip配置的问题。具体安装步骤可以参考一下菜鸟教程上的步骤
